version: '3.8'

services:
  app:
    image: php:8.4-fpm
    container_name: laravel
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "8000:80"
    command: bash -c "composer install && php artisan key:generate && php-fpm"

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
