services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oauth_laravel
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
    networks:
      - laravel_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: oauth_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: oauth_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
  vendor:
  public:
